// #TestTree
// Generates spec/test-tree.md — a Category > Feature > Scenario map of every
// Gherkin file in the repo, each scenario linking to its file:line and each
// feature carrying the one-line purpose from its header comment. Run it with
// `bun run gen:test-tree` (from src/); a guard test keeps the committed file
// fresh. Pure string-building from the .feature sources — no deps.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const SPEC_DIR = dirname(fileURLToPath(import.meta.url));

interface Scenario { name: string; line: number; tags: string[] }
interface FeatureDoc { rel: string; title: string; note: string; scenarios: Scenario[] }

/** First sentence of the feature's header comment block (the `#` lines above
 *  `Feature:`), with bare `#Tag` area-markers dropped. */
function headerNote(lines: string[]): string {
  const out: string[] = [];
  for (const raw of lines) {
    const line = raw.trim();
    if (line.startsWith('#')) {
      const text = line.replace(/^#+\s?/, '').trim();
      if (text && !/^#\w/.test(text)) out.push(text); // skip `#AreaTag` markers
    } else if (line === '') {
      if (out.length) break; // blank after a comment block ends the header
    } else {
      break; // hit Feature:/Rule:/etc.
    }
  }
  const joined = out.join(' ');
  const dot = joined.indexOf('. ');
  return dot === -1 ? joined : joined.slice(0, dot + 1);
}

function parseFeature(abs: string, rel: string): FeatureDoc {
  const lines = readFileSync(abs, 'utf8').split('\n');
  const title = (lines.find((l) => l.trimStart().startsWith('Feature:')) ?? 'Feature:')
    .trim().replace(/^Feature:\s*/, '');
  const scenarios: Scenario[] = [];
  for (let i = 0; i < lines.length; i++) {
    const m = lines[i]!.match(/^\s*(?:Scenario|Scenario Outline):\s*(.+?)\s*$/);
    if (!m) continue;
    const prev = (lines[i - 1] ?? '').trim();
    const tags = prev.startsWith('@') ? prev.split(/\s+/).filter((t) => t.startsWith('@')) : [];
    scenarios.push({ name: m[1]!, line: i + 1, tags });
  }
  return { rel, title, note: headerNote(lines), scenarios };
}

function featuresIn(dir: string, relBase: string): FeatureDoc[] {
  return readdirSync(dir)
    .filter((n) => n.endsWith('.feature'))
    .sort()
    .map((n) => parseFeature(join(dir, n), `${relBase}/${n}`));
}

function section(heading: string, blurb: string, docs: FeatureDoc[]): string {
  const lines = [`## ${heading}`, '', blurb, ''];
  for (const f of docs) {
    const note = f.note ? ` — ${f.note}` : '';
    lines.push(`- **${f.rel.split('/').pop()}** — ${f.title}${note}`);
    for (const s of f.scenarios) {
      const tags = s.tags.length ? ` \`${s.tags.join(' ')}\`` : '';
      lines.push(`  - [${s.name}](${f.rel}#L${s.line})${tags}`);
    }
    lines.push('');
  }
  return lines.join('\n');
}

/** Build the full test-tree.md content. Deterministic (files sorted) so the
 *  guard test can diff it against the committed copy. */
export function generateTestTree(specDir: string = SPEC_DIR): string {
  const appDocs = featuresIn(join(specDir, 'test-cases'), 'test-cases');
  const pkgDirs = readdirSync(join(specDir, 'packages'), { withFileTypes: true })
    .filter((d) => d.isDirectory()).map((d) => d.name).sort();
  const pkgDocs = pkgDirs.flatMap((p) => featuresIn(join(specDir, 'packages', p), `packages/${p}`));

  const appCount = appDocs.reduce((n, f) => n + f.scenarios.length, 0);
  const pkgCount = pkgDocs.reduce((n, f) => n + f.scenarios.length, 0);

  return [
    '# Test tree',
    '',
    '<!-- Generated by `bun run gen:test-tree` (src/). Do not edit by hand —',
    '     a guard test (src/tests/test-tree.test.ts) fails if this drifts. -->',
    '',
    'Every Gherkin feature and scenario in the repo, with each scenario linked to',
    'its source line and each feature carrying the one-line purpose from its header.',
    `App behavior lives in \`test-cases/\` (${appCount} scenarios across ${appDocs.length} features);`,
    `library-package behavior in \`packages/\` (${pkgCount} scenarios across ${pkgDocs.length} features).`,
    'Tags after each scenario show which surfaces run it (`@headless`, `@cli`, `@web`),',
    'whether it is a marketing tour (`@tutorial`), and its panel category (`@cat-…`).',
    '',
    section('test-cases/ — application behavior', 'What the CLI / web app does, driven across surfaces.', appDocs),
    section('packages/ — library packages', 'Behavior of the standalone libraries under `src/packages/`.', pkgDocs),
  ].join('\n').replace(/\n{3,}/g, '\n\n').trimEnd() + '\n';
}

if (import.meta.main) {
  const out = join(SPEC_DIR, 'test-tree.md');
  writeFileSync(out, generateTestTree());
  console.log(`wrote ${out}`);
}
