#!/usr/bin/env bun
// #BenchE1
// `bun run bench:e1:report [run…]`: read benchmarks/mcp-e1/runs/*.jsonl (or the
// named runs), write benchmarks/mcp-e1/report.md, print the summary table.
// Offline. A re-run of a scenario appends a new record; the last one counts.
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { reportMarkdown, type E1Record } from './results.ts';

const E1_DIR = join(dirname(fileURLToPath(import.meta.url)), '..', '..', '..', '..', 'benchmarks', 'mcp-e1');
const RUNS_DIR = join(E1_DIR, 'runs');

const wanted = process.argv.slice(2);
const files = existsSync(RUNS_DIR) ? readdirSync(RUNS_DIR).filter((f) => f.endsWith('.jsonl')) : [];
const latest = new Map<string, E1Record>();
for (const f of files) {
  if (wanted.length && !wanted.includes(f.replace(/\.jsonl$/, ''))) continue;
  for (const line of readFileSync(join(RUNS_DIR, f), 'utf8').split('\n')) {
    if (!line.trim()) continue;
    const r = JSON.parse(line) as E1Record;
    latest.set(`${r.run}\u0000${r.feature}\u0000${r.scenario}`, r);
  }
}
if (latest.size === 0) {
  console.error(`No E1 records under ${RUNS_DIR}. Run \`bun run bench:e1\` first.`);
  process.exit(1);
}
const md = reportMarkdown([...latest.values()]);
writeFileSync(join(E1_DIR, 'report.md'), `# E1 report\n\nGenerated by \`bun run bench:e1:report\`. Method: [README.md](README.md).\n\n${md}`);
console.log(md.split('\n## Failures')[0]);
